### PR TITLE
adding RG-E yaml files

### PR DESCRIPTION
**Pull request by raffaelladevita**
Added yaml files for RG-E data processing. Details on the purpose of the different yamls are included as comments at the top of the files

### CODE REVIEW

**Comment by c-dilks** [comment]
`clas12-validation` is now fixed, can you re-trigger the CI? The easiest way is to push an empty commit:
```bash
git commit --allow-empty -m 'ci: trigger'
git push
```

**Comment by c-dilks** [comment]
Well, these YAML files aren't tested in `clas12-validation`; shall we update the list we test? https://github.com/JeffersonLab/clas12-config/blob/main/.github/ci_config_files.json

**Comment by raffaelladevita** [comment]
> `clas12-validation` is now fixed, can you re-trigger the CI? The easiest way is to push an empty commit:
> 
> ```shell
> git commit --allow-empty -m 'ci: trigger'
> git push
> ```

done

**Comment by raffaelladevita** [comment]
These yamls are for real data processing. Can we test them anyway?

**Comment by baltzell** [comment]
do we still need more config files here?

**Pull request closed without merging**
